apiVersion: v1
data:
  {{- if .Values.auth }}
  htpasswd: |
  {{- range .Values.auth }}
  {{ . | indent 2 }}
  {{- end }}
  {{- end }}
  nginx.conf: |
    events {
      worker_connections  1024;
    }
    http {
      server_tokens off;
      {{- if .Values.configurations }}
      {{- range .Values.configurations }}
      {{ .type }}{{- if .name }} {{ .name }}{{- end }} {
{{ .content | indent 8 }}
      }
      {{- end }}
      {{- else }}
      {{- if .Values.auth }}
      auth_basic "Authentication required";
      auth_basic_user_file /etc/nginx/htpasswd;
      {{- end }}
      {{- if and .Values.tls .Values.tls.key .Values.tls.cert }}
      ssl_protocols TLSv1.2;
      ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;
      ssl_prefer_server_ciphers on;
      server {
        listen 80;
        location / {
          return 301 https://$server_name:{{ include "nginx-sofixit.redirect_port" . }}$request_uri;
        }
      }
      {{- end }}
      server {
        {{ include "nginx-sofixit.server_port" . }}
        root /var/www;
        error_page 404 /error/404;
        error_page 403 /error/403;
        location = / {
          index index.html;
        }
        location / {
          try_files $uri =404;
        }
        location /error/404 {
          return 404 "nothing found here $request_uri";
        }
        location /error/403 {
          return 403 "You are not authenticated!";
        }
      }
      {{- end }}
    }
kind: ConfigMap
metadata:
  name: nginx-config
{{- if and .Values.tls.key .Values.tls.cert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-ssl
type: Opaque
data:
  key: {{ .Values.tls.key }}
  cert: {{ .Values.tls.cert }}
{{- end }}
